import { describe, it, expect } from 'vitest';
import {
  detectDuplicate,
  normalizeMerchant,
  areMerchantsSimilar,
  descriptionsOverlap,
  isAutoGenerated,
  levenshtein,
  type NewTxInput,
} from './duplicateDetection';
import type { Expense } from '@/types/expense';


const baseExpense = (overrides: Partial<Expense>): Expense =>
  ({
    id: 'e1',
    user_id: 'u1',
    amount: 50,
    description: 'Konzum kupovina',
    category: 'food',
    date: new Date('2026-05-10T10:00:00Z'),
    type: 'expense',
    payment_source: 'cash',
    merchant_name: 'Konzum d.o.o.',
    created_at: new Date(),
    updated_at: new Date(),
    ...overrides,
  } as unknown as Expense);

const baseTx = (overrides: Partial<NewTxInput>): NewTxInput => ({
  amount: 50,
  type: 'expense',
  date: new Date('2026-05-10T20:00:00Z'),
  description: 'Konzum kupovina',
  merchant_name: 'Konzum',
  payment_source: 'cash',
  ...overrides,
});

describe('duplicateDetection — helpers', () => {
  it('normalizes merchants by stripping suffixes, diacritics, store numbers and geo stop-words', () => {
    // "zagreb" is a geo stop-word → stripped
    expect(normalizeMerchant('Konzum d.o.o. Zagreb 045')).toBe('konzum');
    expect(normalizeMerchant('KONZUM ZAGREB 045')).toBe('konzum');
    expect(normalizeMerchant('Šibenska pekara')).toBe('sibenska pekara');
    // Geo stop-words removed
    expect(normalizeMerchant('LUKOIL POLJUD/SPLIT/HRV')).toBe('lukoil poljud');
    expect(normalizeMerchant('LESNINA H PC SPLIT')).toBe('lesnina h pc');
  });

  it('matches similar merchants across formatting variants', () => {
    expect(areMerchantsSimilar('Konzum d.o.o. Zagreb', 'KONZUM ZAGREB 045')).toBe(true);
    expect(areMerchantsSimilar('Konzum', 'Lidl')).toBe(false);
  });

  it('does NOT match unrelated merchants that only share a city name', () => {
    // The bug we fixed: LUKOIL ≠ LESNINA even though both contain "SPLIT"
    expect(areMerchantsSimilar('LUKOIL POLJUD/SPLIT/HRV', 'LESNINA H PC SPLIT')).toBe(false);
    expect(areMerchantsSimilar('SPLIT - SUPETAR', 'LIDL HRVATSKA 215 Split')).toBe(false);
    expect(areMerchantsSimilar('TOMMY ZAGREB', 'KONZUM ZAGREB')).toBe(false);
  });

  it('levenshtein basics', () => {
    expect(levenshtein('konzum', 'konzun')).toBe(1);
    expect(levenshtein('konzum', 'kanzum')).toBe(1);
    expect(levenshtein('abc', 'xyz')).toBe(3);
  });
});

describe('duplicateDetection — levels', () => {
  it('STRICT: exact amount + same day + same merchant + same source → manual mode', () => {
    const existing = baseExpense({});
    const result = detectDuplicate(baseTx({}), [existing], {
      ignoreSameDayDuplicateGuard: false,
    });
    expect(result.level).toBe('strict');
    expect(result.confidence).toBeGreaterThanOrEqual(90);
    expect(result.match?.id).toBe('e1');
  });

  it('FUZZY: exact amount + same merchant but 3 days apart', () => {
    const existing = baseExpense({ date: new Date('2026-05-08T10:00:00Z') });
    const result = detectDuplicate(baseTx({}), [existing], { ignoreSameDayDuplicateGuard: true });
    expect(result.level).toBe('fuzzy');
    expect(result.confidence).toBeGreaterThanOrEqual(60);
    expect(result.confidence).toBeLessThan(90);
  });

  it('SUSPICIOUS: ~3% amount diff, same week, near-identical merchant', () => {
    const existing = baseExpense({
      amount: 51.5,
      date: new Date('2026-05-08T10:00:00Z'),
      merchant_name: 'Konzun',
    });
    const result = detectDuplicate(baseTx({}), [existing], { ignoreSameDayDuplicateGuard: true });
    expect(result.level).toBe('suspicious');
    expect(result.confidence).toBeGreaterThanOrEqual(30);
    expect(result.confidence).toBeLessThan(60);
  });

  it('UNIQUE: completely different transaction', () => {
    const existing = baseExpense({ amount: 200, merchant_name: 'Lidl' });
    const result = detectDuplicate(
      baseTx({ amount: 12, merchant_name: 'Tisak' }),
      [existing],
      { ignoreSameDayDuplicateGuard: true }
    );
    expect(result.level).toBe('unique');
    expect(result.confidence).toBe(0);
    expect(result.match).toBeNull();
  });
});

describe('duplicateDetection — edge cases', () => {
  it('CSV import: two identical Konzum purchases same day → SUSPICIOUS, not strict', () => {
    const morning = baseExpense({ date: new Date('2026-05-10T08:00:00Z') });
    const evening = baseTx({ date: new Date('2026-05-10T20:00:00Z') });
    const result = detectDuplicate(evening, [morning], { ignoreSameDayDuplicateGuard: true });
    expect(result.level).toBe('suspicious');
  });

  it('Manual entry: same Konzum same day → STRICT (double-click guard)', () => {
    const existing = baseExpense({ date: new Date('2026-05-10T08:00:00Z') });
    const dup = baseTx({ date: new Date('2026-05-10T08:00:05Z') });
    const result = detectDuplicate(dup, [existing], { ignoreSameDayDuplicateGuard: false });
    expect(result.level).toBe('strict');
  });

  it('Different transaction type never matches as strict', () => {
    const existing = baseExpense({ type: 'income' as any });
    const result = detectDuplicate(baseTx({ type: 'expense' }), [existing], {
      ignoreSameDayDuplicateGuard: false,
    });
    expect(result.level).toBe('unique');
  });

  it('Different store of same chain with different amount → UNIQUE', () => {
    const existing = baseExpense({
      amount: 80,
      merchant_name: 'Konzum Split',
      date: new Date('2026-05-10T10:00:00Z'),
    });
    const result = detectDuplicate(
      baseTx({ amount: 50, merchant_name: 'Konzum Zagreb' }),
      [existing],
      { ignoreSameDayDuplicateGuard: true }
    );
    // Amount differs by 60% → not strict, not fuzzy. Could be suspicious only if
    // within 5%, which fails — so unique.
    expect(result.level).toBe('unique');
  });

  it('Exact amount, same day, same merchant, DIFFERENT payment source → fuzzy', () => {
    const existing = baseExpense({ payment_source: 'cash' });
    const result = detectDuplicate(
      baseTx({ payment_source: 'custom:abc' }),
      [existing],
      { ignoreSameDayDuplicateGuard: false }
    );
    expect(result.level).toBe('fuzzy');
  });

  it('Returns the strongest match when multiple candidates exist', () => {
    const weak = baseExpense({ id: 'weak', amount: 49, date: new Date('2026-05-08T10:00:00Z') });
    const strong = baseExpense({ id: 'strong' });
    const result = detectDuplicate(baseTx({}), [weak, strong], {
      ignoreSameDayDuplicateGuard: false,
    });
    expect(result.match?.id).toBe('strong');
  });
});

describe('duplicateDetection — helper edge cases', () => {
  it('normalizeMerchant handles empty/whitespace', () => {
    expect(normalizeMerchant('')).toBe('');
    expect(normalizeMerchant('   ')).toBe('');
  });

  it('areMerchantsSimilar returns false on null/empty', () => {
    expect(areMerchantsSimilar(null, 'Konzum')).toBe(false);
    expect(areMerchantsSimilar('Konzum', null)).toBe(false);
    expect(areMerchantsSimilar('', 'Konzum')).toBe(false);
    expect(areMerchantsSimilar(undefined, undefined)).toBe(false);
  });

  it('areMerchantsSimilar handles single-letter strings safely', () => {
    expect(areMerchantsSimilar('a', 'b')).toBe(false);
  });

  it('descriptionsOverlap basics', () => {
    expect(descriptionsOverlap('kava i pecivo', 'kava')).toBe(true);
    expect(descriptionsOverlap('kava', 'kava')).toBe(true);
    expect(descriptionsOverlap('kava', 'cola')).toBe(false);
    expect(descriptionsOverlap('', 'cola')).toBe(false);
    expect(descriptionsOverlap(null, null)).toBe(false);
  });

  it('levenshtein edge cases', () => {
    expect(levenshtein('', '')).toBe(0);
    expect(levenshtein('', 'abc')).toBe(3);
    expect(levenshtein('abc', '')).toBe(3);
    expect(levenshtein('konzum', 'konzum')).toBe(0);
  });

  it('isAutoGenerated detects auto-recurring suffixes (multilang)', () => {
    expect(isAutoGenerated({ note: 'Mjesečna pretplata (auto)' } as Expense)).toBe(true);
    expect(isAutoGenerated({ note: 'Generated automatski' } as Expense)).toBe(true);
    expect(isAutoGenerated({ note: 'Ponavljajuća stavka' } as Expense)).toBe(true);
    expect(isAutoGenerated({ note: 'auto-generated' } as Expense)).toBe(true);
    expect(isAutoGenerated({ note: 'Obična bilješka' } as Expense)).toBe(false);
    expect(isAutoGenerated({ note: null } as Expense)).toBe(false);
    expect(isAutoGenerated({} as Expense)).toBe(false);
  });
});

describe('detectDuplicate — boundary scenarios', () => {
  it('returns unique on empty candidate list', () => {
    const tx: NewTxInput = {
      amount: 50,
      type: 'expense',
      date: new Date('2026-05-10'),
      description: 'Konzum',
      merchant_name: 'Konzum',
      payment_source: 'cash',
    };
    const result = detectDuplicate(tx, []);
    expect(result.level).toBe('unique');
    expect(result.match).toBeNull();
  });

  it('zero-amount transaction does not throw and is handled', () => {
    const existing = baseExpense({ amount: 0 });
    const result = detectDuplicate(baseTx({ amount: 0 }), [existing], {
      ignoreSameDayDuplicateGuard: false,
    });
    // Both zero → exact amount, same day, same merchant → strict
    expect(result.level).toBe('strict');
  });

  it('1-cent diff is within 5% for large amounts → suspicious if other signals match', () => {
    const existing = baseExpense({
      amount: 100,
      date: new Date('2026-05-09'),
      merchant_name: 'Konzum',
    });
    const result = detectDuplicate(
      baseTx({ amount: 100.01, date: new Date('2026-05-10') }),
      [existing],
      { ignoreSameDayDuplicateGuard: true }
    );
    // amtDelta=0.01 → not exact, but within5pct → suspicious tier
    expect(['suspicious', 'fuzzy', 'strict']).toContain(result.level);
  });

  it('over 5% diff outside same week → unique', () => {
    const existing = baseExpense({
      amount: 100,
      date: new Date('2026-04-01'),
    });
    const result = detectDuplicate(
      baseTx({ amount: 200, date: new Date('2026-05-10') }),
      [existing],
      { ignoreSameDayDuplicateGuard: true }
    );
    expect(result.level).toBe('unique');
  });

  it('same amount but completely different merchant → unique', () => {
    const existing = baseExpense({ merchant_name: 'Lidl', description: 'Sok' });
    const result = detectDuplicate(
      baseTx({ merchant_name: 'Tisak', description: 'Karta ZET' }),
      [existing],
      { ignoreSameDayDuplicateGuard: false }
    );
    expect(result.level).toBe('unique');
  });

  it('missing merchants but matching description → still strict if same day + amount', () => {
    const existing = baseExpense({ merchant_name: null, description: 'Kava espresso' });
    const result = detectDuplicate(
      baseTx({ merchant_name: null, description: 'Kava espresso' }),
      [existing],
      { ignoreSameDayDuplicateGuard: false }
    );
    expect(result.level).toBe('strict');
  });

  it('null payment_source on one side downgrades nothing (matches via merchant)', () => {
    const existing = baseExpense({ payment_source: null as any });
    const result = detectDuplicate(baseTx({ payment_source: 'cash' }), [existing], {
      ignoreSameDayDuplicateGuard: false,
    });
    // Only one side has payment_source → no source comparison penalty → strict
    expect(result.level).toBe('strict');
  });
});
