project_id = "fzalxjretvtvokiotvkf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.parse-receipt]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.notify-pending-transaction]
verify_jwt = false

[functions.notify-note-added]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = false

[functions.respond-to-invitation]
verify_jwt = false

[functions.auto-reject-pending]
verify_jwt = false

[functions.notify-project-transaction]
verify_jwt = false

[functions.check-budget-alerts]
verify_jwt = false

[functions.categorize-transaction]
verify_jwt = false