import { useCallback, useMemo } from 'react';
import { Expense } from '@/types/expense';
import { ParsedTransaction } from '@/lib/csvParsers';
import { useExpenseFetch } from './useExpenseFetch';
import { useExpenseCRUD } from './useExpenseCRUD';
import { detectDuplicate, isAutoGenerated, type DuplicateMatch } from '@/lib/duplicateDetection';
import { matchManualToImported } from '@/lib/manualMatchForImport';

interface UseExpensesOptions {
  onBalanceUpdated?: () => void;
}

export const useExpenses = (options?: UseExpensesOptions) => {
  const {
    expenses,
    rawExpenses,
    dashboardExpenses,
    hiddenPaymentSourceIds,
    loading,
    isLocalMode,
    setExpenses,
    refetch,
  } = useExpenseFetch();

  const { addExpense, updateExpense, bulkUpdateExpenses, deleteExpense, importFromCSV } =
    useExpenseCRUD({
      isLocalMode,
      expenses,
      setExpenses,
      onBalanceUpdated: options?.onBalanceUpdated,
    });

  /**
   * Bulk import (CSV/PDF) — uses centralized detectDuplicate with
   * `ignoreSameDayDuplicateGuard: true`. Suspicious matches (same-day,
   * same-amount, same-merchant) get their own bucket so the import UI defaults
   * them to "skip" instead of silently importing.
   *
   * Routing:
   *   strict + auto-generated existing → autoGenMatches (offer "replace auto")
   *   strict (normal)                  → duplicates  (auto-skip)
   *   fuzzy                            → fuzzyDuplicates (review, default off)
   *   suspicious                       → suspiciousDuplicates (review, default off)
   *   unique                           → unique
   */
  const findDuplicates = useCallback((transactions: ParsedTransaction[]): {
    duplicates: ParsedTransaction[];
    fuzzyDuplicates: ParsedTransaction[];
    fuzzyMatchedExpenses: Expense[];
    suspiciousDuplicates: ParsedTransaction[];
    suspiciousMatchedExpenses: Expense[];
    autoGenMatches: { tx: ParsedTransaction; existing: Expense }[];
    unique: ParsedTransaction[];
  } => {
    const duplicates: ParsedTransaction[] = [];
    const fuzzyDuplicates: ParsedTransaction[] = [];
    const fuzzyMatchedExpenses: Expense[] = [];
    const suspiciousDuplicates: ParsedTransaction[] = [];
    const suspiciousMatchedExpenses: Expense[] = [];
    const autoGenMatches: { tx: ParsedTransaction; existing: Expense }[] = [];
    const unique: ParsedTransaction[] = [];

    for (const tx of transactions) {
      const txDate = tx.date instanceof Date ? tx.date : new Date(tx.date);
      const match = detectDuplicate(
        {
          amount: tx.amount,
          type: tx.type,
          date: txDate,
          description: tx.description,
          merchant_name: tx.merchant_name,
          payment_source: (tx as any).payment_source ?? null,
        },
        expenses,
        { ignoreSameDayDuplicateGuard: true }
      );

      if (match.level === 'strict' && match.match) {
        if (isAutoGenerated(match.match)) {
          autoGenMatches.push({ tx, existing: match.match });
        } else {
          duplicates.push(tx);
        }
      } else if (match.level === 'fuzzy' && match.match) {
        fuzzyDuplicates.push(tx);
        fuzzyMatchedExpenses.push(match.match);
      } else if (match.level === 'suspicious' && match.match) {
        suspiciousDuplicates.push(tx);
        suspiciousMatchedExpenses.push(match.match);
      } else {
        unique.push(tx);
      }
    }

    return {
      duplicates,
      fuzzyDuplicates,
      fuzzyMatchedExpenses,
      suspiciousDuplicates,
      suspiciousMatchedExpenses,
      autoGenMatches,
      unique,
    };
  }, [expenses]);

  /**
   * Manual entry / receipt scan — strict guard against accidental double
   * submission. Returns the existing Expense only when the central detector
   * classifies the pair as `strict`.
   */
  const checkDuplicate = useCallback((transaction: {
    amount: number;
    description: string;
    date: Date;
    type: string;
    category?: string;
    merchant_name?: string;
    payment_source?: string;
  }): Expense | null => {
    const match = detectDuplicate(
      {
        amount: transaction.amount,
        type: transaction.type,
        date: transaction.date,
        description: transaction.description,
        merchant_name: transaction.merchant_name,
        payment_source: transaction.payment_source ?? null,
      },
      expenses,
      { ignoreSameDayDuplicateGuard: false }
    );
    return match.level === 'strict' ? match.match : null;
  }, [expenses]);

  /** Full DuplicateMatch for UI surfaces that want to render level/reason. */
  const inspectDuplicate = useCallback((transaction: {
    amount: number;
    description: string;
    date: Date;
    type: string;
    merchant_name?: string;
    payment_source?: string;
  }): DuplicateMatch => {
    return detectDuplicate(
      {
        amount: transaction.amount,
        type: transaction.type,
        date: transaction.date,
        description: transaction.description,
        merchant_name: transaction.merchant_name,
        payment_source: transaction.payment_source ?? null,
      },
      expenses,
      { ignoreSameDayDuplicateGuard: false }
    );
  }, [expenses]);

  const totals = useMemo(() => {
    const now = new Date();
    const currentMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const currentMonthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

    const totalExpenses = dashboardExpenses
      .filter(e => e.type === 'expense' && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const totalIncome = dashboardExpenses
      .filter(e => e.type === 'income' && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const totalTransfers = dashboardExpenses
      .filter(e => e.type === 'transfer')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const monthlyTransfers = dashboardExpenses
      .filter(e => e.type === 'transfer' && e.date >= currentMonthStart && e.date <= currentMonthEnd)
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const transferCount = dashboardExpenses.filter(e => e.type === 'transfer').length;

    const monthlyTransferCount = dashboardExpenses
      .filter(e => e.type === 'transfer' && e.date >= currentMonthStart && e.date <= currentMonthEnd)
      .length;

    const balance = totalIncome - totalExpenses;

    const expensesByCategory = dashboardExpenses
      .filter(e => e.type === 'expense' && (e.expense_nature as string) !== 'correction')
      .reduce((acc, e) => {
        acc[e.category] = (acc[e.category] || 0) + Number(e.amount);
        return acc;
      }, {} as Record<string, number>);

    return {
      totalExpenses,
      totalIncome,
      totalTransfers,
      monthlyTransfers,
      transferCount,
      monthlyTransferCount,
      balance,
      expensesByCategory,
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dashboardExpenses]);

  // Trend data: compare current month vs previous month using RAW expenses
  const trendData = useMemo(() => {
    const now = new Date();
    const curStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const curEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);
    const prevStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
    const prevEnd = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59);

    const curMonthIncome = expenses
      .filter(e => e.type === 'income' && e.date >= curStart && e.date <= curEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);
    const curMonthExpenses = expenses
      .filter(e => e.type === 'expense' && e.date >= curStart && e.date <= curEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);
    const prevMonthIncome = expenses
      .filter(e => e.type === 'income' && e.date >= prevStart && e.date <= prevEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);
    const prevMonthExpenses = expenses
      .filter(e => e.type === 'expense' && e.date >= prevStart && e.date <= prevEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    return { prevMonthIncome, prevMonthExpenses, curMonthIncome, curMonthExpenses };
  }, [expenses]);

  return {
    expenses: dashboardExpenses,
    allExpenses: expenses,
    rawExpenses,
    hiddenPaymentSourceIds,
    loading,
    isLocalMode,
    addExpense,
    updateExpense,
    bulkUpdateExpenses,
    deleteExpense,
    importFromCSV,
    findDuplicates,
    checkDuplicate,
    inspectDuplicate,
    refetch,
    ...totals,
    ...trendData,
  };
};
