import { useCallback, useMemo } from 'react';
import { Expense } from '@/types/expense';
import { ParsedTransaction } from '@/lib/csvParsers';
import { useExpenseFetch } from './useExpenseFetch';
import { useExpenseCRUD } from './useExpenseCRUD';
import { useCustomPaymentSources } from './useCustomPaymentSources';
import { detectDuplicate, isAutoGenerated, type DuplicateMatch } from '@/lib/duplicateDetection';
import { matchImportRowsBySameExpense, buildCardWalletMap } from '@/lib/importReview/sameExpenseImport';
import { useAuthContext } from '@/contexts/AuthContext';
import { isExpenseType, isIncomeType, isRealIncome, isRealSpend } from '@/lib/spendClassification';

interface UseExpensesOptions {
  onBalanceUpdated?: () => void;
}

export const useExpenses = (options?: UseExpensesOptions) => {
  const {
    expenses,
    rawExpenses,
    dashboardExpenses,
    hiddenPaymentSourceIds,
    loading,
    isLocalMode,
    setExpenses,
    refetch,
  } = useExpenseFetch();

  // Foundation Plan, Val 1: collect ALL custom payment source IDs available to
  // the user (own + shared via membership + cross-mode personal in business
  // mode). Passed into useExpenseCRUD so payment_source normalization can
  // validate `custom:UUID` references at every write chokepoint.
  const { customPaymentSources } = useCustomPaymentSources({ includePersonal: true });
  const { user } = useAuthContext();
  const cardWallets = useMemo(() => buildCardWalletMap(customPaymentSources), [customPaymentSources]);
  const knownCustomSourceIds = useMemo<ReadonlySet<string>>(
    () => new Set(customPaymentSources.map((s) => s.id)),
    [customPaymentSources],
  );

  const { addExpense, updateExpense, bulkUpdateExpenses, deleteExpense, importFromCSV } =
    useExpenseCRUD({
      isLocalMode,
      expenses,
      setExpenses,
      onBalanceUpdated: options?.onBalanceUpdated,
      knownCustomSourceIds,
    });

  /**
   * Bulk import (CSV/PDF) — uses centralized detectDuplicate with
   * `ignoreSameDayDuplicateGuard: true`. Suspicious matches (same-day,
   * same-amount, same-merchant) get their own bucket so the import UI defaults
   * them to "skip" instead of silently importing.
   *
   * Routing:
   *   strict + auto-generated existing → autoGenMatches (offer "replace auto")
   *   strict (normal)                  → duplicates  (auto-skip)
   *   fuzzy                            → fuzzyDuplicates (review, default off)
   *   suspicious                       → suspiciousDuplicates (review, default off)
   *   unique                           → unique
   */
  const findDuplicates = useCallback((transactions: ParsedTransaction[]): {
    duplicates: ParsedTransaction[];
    fuzzyDuplicates: ParsedTransaction[];
    fuzzyMatchedExpenses: Expense[];
    suspiciousDuplicates: ParsedTransaction[];
    suspiciousMatchedExpenses: Expense[];
    autoGenMatches: { tx: ParsedTransaction; existing: Expense }[];
    autoMergeMatches: { tx: ParsedTransaction; existing: Expense }[];
    unique: ParsedTransaction[];
  } => {
    const duplicates: ParsedTransaction[] = [];
    const fuzzyDuplicates: ParsedTransaction[] = [];
    const fuzzyMatchedExpenses: Expense[] = [];
    const suspiciousDuplicates: ParsedTransaction[] = [];
    const suspiciousMatchedExpenses: Expense[] = [];
    const autoGenMatches: { tx: ParsedTransaction; existing: Expense }[] = [];
    const autoMergeMatches: { tx: ParsedTransaction; existing: Expense }[] = [];
    const unique: ParsedTransaction[] = [];

    // ── Auto-merge prelim: same logic the import flow runs server-side after
    // user confirms. We surface it in the dialog so the user knows these will
    // be silently merged into existing manual entries (not duplicated).
    // Pravilo „isti trošak" (auto, cijela datoteka = jedan batch) — ISTO
    // pravilo koje importFromCSV primjenjuje pri upisu. Samo `match`.
    const mergeCandidates = transactions
      .map((tx, idx) => ({
        index: idx,
        paymentSource: (tx as any).payment_source ?? null,
        type: tx.type,
        amount: tx.amount,
        date: tx.date instanceof Date ? tx.date : new Date(tx.date),
        merchantName: tx.merchant_name ?? null,
        description: tx.description ?? null,
      }));
    const manualPool = expenses.filter(e => {
      const status = (e as any).bank_match_status;
      if (status && status !== 'manual' && status !== 'pending_bank') return false;
      if ((e as any).bank_transaction_id) return false;
      return isIncomeType(e) || isExpenseType(e) || e.type === 'transfer';
    });
    const mergeResult = user
      ? matchImportRowsBySameExpense(
          { userId: user.id, cardWallets },
          mergeCandidates,
          manualPool.map(e => ({
            id: e.id,
            userId: e.user_id,
            paymentSource: e.payment_source ?? null,
            type: e.type,
            amount: Number(e.amount),
            date: e.date instanceof Date ? e.date : new Date(e.date),
            merchantName: e.merchant_name ?? null,
            description: e.description ?? null,
            cardId: e.payment_source_card_id ?? null,
            expenseNature: e.expense_nature ?? null,
            isAdvance: e.is_advance ?? null,
            linkedAdvanceIds: e.linked_advance_ids ?? null,
            bankMatchStatus: (e as any).bank_match_status ?? null,
          })),
        )
      : { matches: [] as Array<{ importedIndex: number; manualId: string }> };
    const autoMergeByIndex = new Map<number, Expense>();
    for (const m of mergeResult.matches) {
      const existing = manualPool.find(e => e.id === m.manualId);
      if (existing) autoMergeByIndex.set(m.importedIndex, existing);
    }

    transactions.forEach((tx, idx) => {
      // Route auto-merge first — it always wins over fuzzy/suspicious so we don't
      // double-warn the user about transactions that will be silently merged.
      const autoMergeExisting = autoMergeByIndex.get(idx);
      if (autoMergeExisting) {
        autoMergeMatches.push({ tx, existing: autoMergeExisting });
        return;
      }

      const txDate = tx.date instanceof Date ? tx.date : new Date(tx.date);
      const match = detectDuplicate(
        {
          amount: tx.amount,
          type: tx.type,
          date: txDate,
          description: tx.description,
          merchant_name: tx.merchant_name,
          payment_source: (tx as any).payment_source ?? null,
        },
        expenses,
        { ignoreSameDayDuplicateGuard: true }
      );

      if (match.level === 'strict' && match.match) {
        if (isAutoGenerated(match.match)) {
          autoGenMatches.push({ tx, existing: match.match });
        } else {
          duplicates.push(tx);
        }
      } else if (match.level === 'fuzzy' && match.match) {
        fuzzyDuplicates.push(tx);
        fuzzyMatchedExpenses.push(match.match);
      } else if (match.level === 'suspicious' && match.match) {
        suspiciousDuplicates.push(tx);
        suspiciousMatchedExpenses.push(match.match);
      } else {
        unique.push(tx);
      }
    });

    return {
      duplicates,
      fuzzyDuplicates,
      fuzzyMatchedExpenses,
      suspiciousDuplicates,
      suspiciousMatchedExpenses,
      autoGenMatches,
      autoMergeMatches,
      unique,
    };
  }, [expenses, user, cardWallets]);

  /**
   * Manual entry / receipt scan — strict guard against accidental double
   * submission. Returns the existing Expense only when the central detector
   * classifies the pair as `strict`.
   */
  const checkDuplicate = useCallback((transaction: {
    amount: number;
    description: string;
    date: Date;
    type: string;
    category?: string;
    merchant_name?: string;
    payment_source?: string;
  }): Expense | null => {
    const match = detectDuplicate(
      {
        amount: transaction.amount,
        type: transaction.type,
        date: transaction.date,
        description: transaction.description,
        merchant_name: transaction.merchant_name,
        payment_source: transaction.payment_source ?? null,
      },
      expenses,
      { ignoreSameDayDuplicateGuard: false }
    );
    return match.level === 'strict' ? match.match : null;
  }, [expenses]);

  /** Full DuplicateMatch for UI surfaces that want to render level/reason. */
  const inspectDuplicate = useCallback((transaction: {
    amount: number;
    description: string;
    date: Date;
    type: string;
    merchant_name?: string;
    payment_source?: string;
  }): DuplicateMatch => {
    return detectDuplicate(
      {
        amount: transaction.amount,
        type: transaction.type,
        date: transaction.date,
        description: transaction.description,
        merchant_name: transaction.merchant_name,
        payment_source: transaction.payment_source ?? null,
      },
      expenses,
      { ignoreSameDayDuplicateGuard: false }
    );
  }, [expenses]);

  const totals = useMemo(() => {
    const now = new Date();
    const currentMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const currentMonthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

    const totalExpenses = dashboardExpenses
      .filter(e => isRealSpend(e) && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const totalIncome = dashboardExpenses
      .filter(e => isRealIncome(e) && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const totalTransfers = dashboardExpenses
      .filter(e => e.type === 'transfer')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const monthlyTransfers = dashboardExpenses
      .filter(e => e.type === 'transfer' && e.date >= currentMonthStart && e.date <= currentMonthEnd)
      .reduce((sum, e) => sum + Number(e.amount), 0);

    const transferCount = dashboardExpenses.filter(e => e.type === 'transfer').length;

    const monthlyTransferCount = dashboardExpenses
      .filter(e => e.type === 'transfer' && e.date >= currentMonthStart && e.date <= currentMonthEnd)
      .length;

    const balance = totalIncome - totalExpenses;

    const expensesByCategory = dashboardExpenses
      .filter(e => isRealSpend(e) && (e.expense_nature as string) !== 'correction')
      .reduce((acc, e) => {
        acc[e.category] = (acc[e.category] || 0) + Number(e.amount);
        return acc;
      }, {} as Record<string, number>);

    return {
      totalExpenses,
      totalIncome,
      totalTransfers,
      monthlyTransfers,
      transferCount,
      monthlyTransferCount,
      balance,
      expensesByCategory,
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dashboardExpenses]);

  // Trend data: compare current month vs previous month using RAW expenses
  const trendData = useMemo(() => {
    const now = new Date();
    const curStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const curEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);
    const prevStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
    const prevEnd = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59);

    const curMonthIncome = expenses
      .filter(e => isRealIncome(e) && e.date >= curStart && e.date <= curEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);
    const curMonthExpenses = expenses
      .filter(e => isRealSpend(e) && e.date >= curStart && e.date <= curEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);
    const prevMonthIncome = expenses
      .filter(e => isRealIncome(e) && e.date >= prevStart && e.date <= prevEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);
    const prevMonthExpenses = expenses
      .filter(e => isRealSpend(e) && e.date >= prevStart && e.date <= prevEnd && (e.expense_nature as string) !== 'correction')
      .reduce((sum, e) => sum + Number(e.amount), 0);

    return { prevMonthIncome, prevMonthExpenses, curMonthIncome, curMonthExpenses };
  }, [expenses]);

  return {
    expenses: dashboardExpenses,
    allExpenses: expenses,
    rawExpenses,
    hiddenPaymentSourceIds,
    loading,
    isLocalMode,
    addExpense,
    updateExpense,
    bulkUpdateExpenses,
    deleteExpense,
    importFromCSV,
    findDuplicates,
    checkDuplicate,
    inspectDuplicate,
    refetch,
    ...totals,
    ...trendData,
  };
};
