// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-recent-expenses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_expenses_default = defineTool({
  name: "list_recent_expenses",
  title: "List recent transactions",
  description: "List the signed-in user's most recent transactions (expenses, income, transfers) from V&M Balance, newest first.",
  inputSchema: {
    limit: z.number().int().describe("How many rows to return (1-50). Defaults to 20.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const capped = Math.max(1, Math.min(50, Math.floor(limit ?? 20)));
    const { data, error } = await supabaseForUser(ctx).from("expenses").select(
      "id,date,event_at,type,amount,currency,category,description,merchant_name,payment_source"
    ).is("deleted_at", null).order("date", { ascending: false }).limit(capped);
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-wallet-balances.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_wallet_balances_default = defineTool2({
  name: "get_wallet_balances",
  title: "Get wallet balances",
  description: "Return the signed-in user's custom payment sources (wallets) with their current stored balance and currency.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser2(ctx).from("custom_payment_sources").select("id,name,balance,currency,type").order("name", { ascending: true });
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { wallets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-expense.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_expense_default = defineTool3({
  name: "create_expense",
  title: "Create expense",
  description: "Insert a new expense (tro\u0161ka) for the signed-in user in V&M Balance. Amount is a positive number in the given currency. Date is ISO (YYYY-MM-DD). Category is a free-form string.",
  inputSchema: {
    amount: z2.number().positive().describe("Positive amount (e.g. 12.50)"),
    currency: z2.string().describe("ISO 4217 currency code, e.g. 'EUR'. Defaults to 'EUR'."),
    date: z2.string().describe("ISO date YYYY-MM-DD. Defaults to today if omitted."),
    category: z2.string().describe("Category name, e.g. 'groceries'."),
    description: z2.string().describe("Short description / merchant note."),
    payment_source: z2.string().describe(
      "Payment source id. Either a system id like 'cash' or 'custom:<uuid>' for a user wallet. Defaults to 'cash'."
    )
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const row = {
      user_id: ctx.getUserId(),
      type: "expense",
      amount: input.amount,
      currency: (input.currency ?? "EUR").toUpperCase(),
      date: input.date ?? today,
      category: input.category ?? "other",
      description: input.description ?? "",
      payment_source: input.payment_source ?? "cash"
    };
    const { data, error } = await supabaseForUser3(ctx).from("expenses").insert(row).select().single();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: `Created expense ${data?.id ?? ""}` }
      ],
      structuredContent: { expense: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fzalxjretvtvokiotvkf";
var mcp_default = defineMcp({
  name: "vm-balance-mcp",
  title: "V&M Balance MCP",
  version: "0.1.0",
  instructions: "Tools for V&M Balance, a personal & small-business finance app. Use `list_recent_expenses` to fetch the signed-in user's recent transactions, `get_wallet_balances` to see their payment sources, and `create_expense` to record a new expense.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_expenses_default, get_wallet_balances_default, create_expense_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
